#define BREAK 0
#define CONTINUE 1
#define ELSE 2
#define IF 3
#define INT 4
#define RETURN 5
#define WHILE 6
#define PRINTF 7
#define ADD 10
#define MINUS 11
#define TIMES 12
#define DIV 13
#define MOD 14
#define NOT 15
#define QUES 16
#define COLON 17
#define ASSIGN 28
#define COMMA 19
#define LT 20
#define GT 21
#define LP 22
#define RP 23
#define LSP 24
#define RSP 25
#define OR 26
#define AND 27
#define EQ 18
#define QUOTE 29
#define SEMI 30
#define ID 31
#define NUM 32
#define STRING 9
#define COMMENT 8
#define ERROR (-1)

extern int yylex(); 
extern FILE *yyin; 

extern char c_name[16]; 
extern int c_val; 
